### ISSUE TITLE
pls always use spaces instead of tabs.

### ISSUE THREAD

**Issue by jason-weirather** [treefroog/tapir-bot#9]
u

**Comment by RossSmyth** [comment]
no u

**Comment by jason-weirather** [comment]
😭 rip me

**Comment by RossSmyth** [comment]
I'll pay you in Github stars

**Comment by RossSmyth** [comment]
Maybe @bartti can help you out

**Comment by RossSmyth** [comment]
Closing due to 4b75ab53be8b62953dd486cb68d917e330d60e60 "fixing" this non-issue. I don't even know why I put the 30 seconds into this. I blame @bartti for all problems
